plugins {
    id 'com.android.application'
}

android {
    namespace 'uk.scanaki.kitchen'
    compileSdk 36

    defaultConfig {
        applicationId 'uk.scanaki.kitchen'
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName '0.2.1'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
